In [1]:
import pandas as pd


In [2]:
pd.__version__

'1.4.3'

In [3]:
# Series
a = [1,2,3]
pSeries = pd.Series(a)
print(pSeries)
print(pSeries[0]) #
print(pSeries[1])
print(pSeries[2]) #Index
pSeries = pd.Series(a, index = [1,2,3]) #Labelling
print(pSeries)
print(pSeries[1]) #
print(pSeries[2]) #Labels

0    1
1    2
2    3
dtype: int64
1
2
3
1    1
2    2
3    3
dtype: int64
1
2


In [4]:
# Keys/Object pairs as Series
calorie = {"day1": 420, "day2": 450, "day3": 370}
pCalorie = pd.Series(calorie)
print(pCalorie)

day1    420
day2    450
day3    370
dtype: int64


In [5]:
# DataFrame
data = {
    "calories": [420, 380, 390],
    "duration": [50, 40, 45]
}
pDataFrame = pd.DataFrame(data, index = ["day1", "day2", "day3"]) # Named Index
print(pDataFrame)

      calories  duration
day1       420        50
day2       380        40
day3       390        45


In [6]:
print(pDataFrame.loc["day1"]) # Locate a Row

calories    420
duration     50
Name: day1, dtype: int64


In [7]:
print(pDataFrame["calories"]["day2"])

380


In [8]:
sheet = pd.read_csv("cardata.csv")
print(sheet)

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0

In [9]:
print(sheet)
print(sheet["Present_Price"])
print(sheet["Present_Price"].mean())

    Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0       ritz  2014           3.35           5.59       27000    Petrol   
1        sx4  2013           4.75           9.54       43000    Diesel   
2       ciaz  2017           7.25           9.85        6900    Petrol   
3    wagon r  2011           2.85           4.15        5200    Petrol   
4      swift  2014           4.60           6.87       42450    Diesel   
..       ...   ...            ...            ...         ...       ...   
296     city  2016           9.50          11.60       33988    Diesel   
297     brio  2015           4.00           5.90       60000    Petrol   
298     city  2009           3.35          11.00       87934    Petrol   
299     city  2017          11.50          12.50        9000    Diesel   
300     brio  2016           5.30           5.90        5464    Petrol   

    Seller_Type Transmission  Owner  
0        Dealer       Manual      0  
1        Dealer       Manual      0

In [10]:
smi = pd.read_csv("Book1.csv")

In [11]:
smi

Quiz 1  Mid sem  Quiz 2  End sem
0     11.0     13.0    12.0     40.0
1      7.0      6.5     2.5     23.0
2      9.5     12.0     8.5     29.0
3     10.0      9.5    10.0     34.0
4      8.5     15.5    10.0     33.0
..     ...      ...     ...      ...
90     8.0      8.0     5.5     26.0
91     8.5      7.0     8.0     13.0
92    10.5     13.0     8.0     36.0
93     2.0     11.5    11.5     19.0
94     3.5      2.0     8.0      7.0

[95 rows x 4 columns]

In [12]:
smi["Total"]=smi["Quiz 1"]+smi["Quiz 2"]+smi["Mid sem"]+smi["End sem"]

In [13]:
smisir = smi
print(smisir.mean())

Quiz 1      8.184211
Mid sem    11.305263
Quiz 2      8.947368
End sem    26.731579
Total      55.168421
dtype: float64


In [14]:
print(smisir["Total"].max())
print(smisir["Total"].std())
print(smisir["Total"].max() - smisir["Total"].std())

89.0
17.96181832925523
71.03818167074476


In [15]:
count=0
for i in range (0,95):
    if(smisir["Total"][i]>71.03818167074476):
        count = count +1
print(count)

16


In [16]:
pd.options.display.max_rows=99999919191
print(pd.options.display.max_rows)
print(smi)

99999919191
    Quiz 1  Mid sem  Quiz 2  End sem  Total
0    11.00     13.0    12.0     40.0  76.00
1     7.00      6.5     2.5     23.0  39.00
2     9.50     12.0     8.5     29.0  59.00
3    10.00      9.5    10.0     34.0  63.50
4     8.50     15.5    10.0     33.0  67.00
5     6.50     12.0    11.0     30.0  59.50
6     4.00      7.0     7.5     22.0  40.50
7    10.25     10.0    11.0     39.0  70.25
8     7.75     11.5     9.5     17.5  46.25
9     9.00     10.0     8.0     26.0  53.00
10    6.50      8.0     7.0     21.5  43.00
11    8.00     10.0    12.5     34.5  65.00
12    8.25     11.5    11.0     43.0  73.75
13   13.50      9.0     9.5     30.0  62.00
14    6.00      3.0    12.0     19.0  40.00
15   11.75     10.5    11.5     36.5  70.25
16    8.50     13.5     8.5     36.5  67.00
17   13.50     19.5    11.5     44.0  88.50
18    2.75     10.0     6.0     11.0  29.75
19   12.75     16.0    13.5     43.0  85.25
20    7.25     15.0     6.5     11.0  39.75
21    9.00     11.0 

In [17]:
print(smi.info()) ## To get info of the DataFrame such as no fo colums and Rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Quiz 1   95 non-null     float64
 1   Mid sem  95 non-null     float64
 2   Quiz 2   95 non-null     float64
 3   End sem  95 non-null     float64
 4   Total    95 non-null     float64
dtypes: float64(5)
memory usage: 3.8 KB
None


## Data Cleaning

In [18]:
print(sheet.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Car_Name       301 non-null    object 
 1   Year           301 non-null    int64  
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64  
 5   Fuel_Type      301 non-null    object 
 6   Seller_Type    301 non-null    object 
 7   Transmission   301 non-null    object 
 8   Owner          301 non-null    int64  
dtypes: float64(2), int64(3), object(4)
memory usage: 21.3+ KB
None


## NUMPY DataTypes & Attributes

In [19]:
import numpy as np

In [20]:
a1 = np.array([1,2,3])
print(a1)
print(type(a1))

[1 2 3]
<class 'numpy.ndarray'>


In [21]:
a2 = np.array([ [1,2,3], [2,3,4] ])
a3 = np.array([ [[1,2,3],
                 [2,3,4],
                 [3,4,5]],
                [[4,5,6],
                 [5,6,7],
                 [6,7,8]] ])

In [22]:
print(a2.shape, a3.shape, a2.ndim, a3.ndim, a2.size, a3.size)
print(type(a1), type(a2), type(a3))

(2, 3) (2, 3, 3) 2 3 6 18
<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [23]:
# let us makek array into dataframe
nPractice = pd.DataFrame(a2)
nPractice

0  1  2
0  1  2  3
1  2  3  4

In [24]:
# nPractice0 = pd.DataFrame(a3) --- it is not possible

In [25]:
one = np.ones((5,3,3))
one

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [26]:
RangePractice = np.arange(0,10,5)
RangePractice

array([0, 5])

In [27]:
# random, ranint, rand
nPractice0 = np.random.randint(0,10, size = (2,3,3))
print(nPractice0)
nPractice1 = np.random.random((1,3,3))
print(nPractice1)
nPractice2 = np.random.rand(1,3,3)
print(nPractice2)

[[[1 4 4]
  [6 1 7]
  [6 4 3]]

 [[2 1 2]
  [3 2 5]
  [3 2 9]]]
[[[0.81593688 0.69945498 0.72510175]
  [0.91506027 0.70274066 0.44801624]
  [0.24606661 0.28532732 0.06694579]]]
[[[0.27261392 0.45508141 0.55944565]
  [0.39221936 0.2626768  0.17905043]
  [0.89329779 0.31066314 0.66721505]]]


All these randoms are pseudo randoms

In [28]:
np.random.seed(seed = 69)
nPractice3 = np.random.rand(1,5,3)
nPractice3

array([[[0.29624916, 0.80906772, 0.35025253],
        [0.78940926, 0.56134898, 0.25358895],
        [0.10497708, 0.05846073, 0.67329238],
        [0.69782966, 0.73278321, 0.78787406],
        [0.07637632, 0.3176806 , 0.74102328]]])

In [29]:
nPractice3

array([[[0.29624916, 0.80906772, 0.35025253],
        [0.78940926, 0.56134898, 0.25358895],
        [0.10497708, 0.05846073, 0.67329238],
        [0.69782966, 0.73278321, 0.78787406],
        [0.07637632, 0.3176806 , 0.74102328]]])

In [30]:
np.unique(nPractice3)

array([0.05846073, 0.07637632, 0.10497708, 0.25358895, 0.29624916,
       0.3176806 , 0.35025253, 0.56134898, 0.67329238, 0.69782966,
       0.73278321, 0.74102328, 0.78787406, 0.78940926, 0.80906772])

In [35]:
a2, a1

(array([[1, 2, 3],
        [2, 3, 4]]),
 array([1, 2, 3]))

In [34]:
a2.dot(a1)

array([14, 20])

a1.dot(a2) not possible